### PR TITLE
Fix websocket disconnect after connection loss

### LINKED ISSUE #856: Socket reconnection does not work when internet is restored
We connect over a web socket with a data subscription. And all the data is successfully received.

But when we turn off the Internet connection in the emulator and do not turn on the Internet for more than 5 seconds.

Then after turning on the Internet, this error appears.

And we can't catch her in any way, because we don't know where to do it.

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: WebSocketChannelException: WebSocketChannelException: SocketException: Failed host lookup: '{THIS_MY_GQL_ENDPOINT}' (OS Error: No address associated with hostname, errno = 7)

### PR DESCRIPTION
**Pull request by Bligoubloups**
Changes requested for #888
Fix #856

`platform_stub.dart` was unused as well as `isHtml` and `isIo` booleans.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
HI.

I'm scheduler to review this before the end of the year, can you rebase this PR on master? I like how you managed the export package for each platform.

**Comment by kateile** [comment]
@vincenzopalazzo hi, any progress on this?

**Comment by Bligoubloups** [comment]
Hello @vincenzopalazzo I'm already up to date with master. Did you mean rebase on beta ?

**Comment by vincenzopalazzo** [comment]
>Hello @vincenzopalazzo I'm already up to date with master. Did you mean rebase on beta ?

Yep!

File: packages/graphql/lib/src/links/websocket_link/websocket_client.dart [hunk 1]
```diff
@@ -222,7 +227,7 @@ class SocketClient {
       // Even though config.connect is sync, we call async in order to make the
       // SocketConnectionState.connected attribution not overload SocketConnectionState.connecting
       socketChannel =
-          await config.connect(Uri.parse(url), protocols).forGraphQL();
+          (await config.connect(Uri.parse(url), protocols)).forGraphQL();
```
Comment (vincenzopalazzo) [inline packages/graphql/lib/src/links/websocket_link/websocket_client.dart:230]:
```
var connection = await config.connect(Uri.parse(url), protocols)
suggestion = connection.forGraphQL();
```

This is a more clean way to write the same code, but it is more accessible for people people with disabilities

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
LGTM, but I have only one change request for code style.

Thanks for your work.

**Comment by vytautas-pranskunas-** [comment]
Watching

**Review by vincenzopalazzo — APPROVED** [review]
